aa7

diff --git a/.github/workflows/tag-push.yml b/.github/workflows/tag-push.yml
--- a/.github/workflows/tag-push.yml
+++ b/.github/workflows/tag-push.yml
@@ -4,6 +4,7 @@ on:
   push:
     branches:
       - feat/cicd  # 특정 브랜치 지정
+    
 
 permissions:
   contents: write  # 레포지토리 내용(코드 포함)에 대한 쓰기 권한
@@ -13,12 +14,58 @@ permissions:
 jobs:
   build:
     runs-on: ubuntu-latest
+
     steps:
-      - name: Git 태그 생성 및 푸시
+      - name: Checkout 코드 가져오기
+        uses: actions/checkout@v4
+
+      - name: JDK 21 설정
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'temurin'
+          java-version: '21'
+
+      - name: Gradle 캐싱 설정 (선택 사항)
+        uses: actions/cache@v3
+        with:
+          path: ~/.gradle/caches
+          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
+          restore-keys: |
+            gradle-${{ runner.os }}
+
+      # - name: Gradle 테스트 실행
+      #   id: test
+      #   working-directory: hairgg
+      #   run: |
+      #     set +e
+      #     chmod +x ./gradlew
+      #     ./gradlew -ex | tee test-results.log
+      #     TEST_EXIT_CODE=${PIPESTATUS[0]}
+      #     echo "TEST_RESULT=$(tail -n 10 test-results.log | base64 -w0)" >> $GITHUB_ENV
+      #     exit $TEST_EXIT_CODE
+
+
+      # - name: 테스트 결과 Discord 전송
+      #   uses: Ilshidur/action-discord@master
+      #   with:
+      #     webhook: ${{ secrets.DISCORD_WEBHOOK }}
+      #     message: |
+      #       Spring Boot 테스트 결과:
+      #       ```
+      #       ${{ env.TEST_RESULT }}
+      #       ```
+      #     only_if: failure()  # 실패 시에만 알림 전송
+      - name: Create and push Git tag
         run: |
-          TAG_NAME="v$(date +'%Y%m%d%H%M%S')" 
+          # Git 태그 생성 (버전 태그를 사용하거나 날짜 및 시간으로 고유 태그 생성)
+          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"  # 예: v20250216054030
           git tag $TAG_NAME
           git push origin $TAG_NAME
+      
       - name: Output으로 태그 전달
         id: output
-        run: echo "TAG_NAME=v$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
+        run: |
+          echo "::set-output name=tag_name::${{ env.TAG_NAME }}"  # 출력으로 태그 전달
+
+    outputs:
+      tag_name: ${{ steps.output.outputs.tag_name }}  # tag_name 출력
